//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TrucksReserveEntities : DbContext
    {
        public TrucksReserveEntities()
            : base("name=TrucksReserveEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Category> Categories { get; set; }
        public DbSet<File> Files { get; set; }
        public DbSet<Firm> Firms { get; set; }
        public DbSet<Firm_Category> Firm_Category { get; set; }
        public DbSet<Gallery> Gallery { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Product_Category> Product_Category { get; set; }
        public DbSet<Text> Texts { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
