//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public int ID { get; set; }
        public int Type { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public bool Main { get; set; }
    }
}
